const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#6C63FF",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#6C63FF",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#3A3A3C",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3A3A3C",
    input: "#2C2C2E",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#6C63FF",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#6C63FF",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#3A3A3C",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#3A3A3C",
    input: "#2C2C2E",
  },
  radius: 14,
};

export default colors;
